### ISSUE TITLE
 Error in nls.lm(par = start, fn = FCT, jac = jac, control = control, lower = lower,  :    evaluation of fn function returns non-sensible value! 

### ISSUE THREAD

**Issue by xuebaliang** [VCCRI/CIDR#11]
Hello, recently I use the CIDR package to analysis(cluster) my data, The data has 32061 samples. But I meet this error and do not know how to deal with it. So can you give me some advice?

**Comment by croct** [comment]
I have not come across this error before with CIDR.  You would have to send me the code & some data that reproduces this problem.  Best to contact me with this information at m.troup@victorchang.edu.au

Michael

**Comment by xuebaliang** [comment]
Okok, I send you them just now. I hope you can deal with it. Thanks !

 

 ------------------ 原始邮件 ------------------
  发件人: "Michael Troup"<notifications@github.com>;
 发送时间: 2019年7月16日(星期二) 下午5:34
 收件人: "VCCRI/CIDR"<CIDR@noreply.github.com>;
 抄送: "听杰伦的歌会あなたを思う"<2553159033@qq.com>;"Author"<author@noreply.github.com>;
 主题: Re: [VCCRI/CIDR] Error in nls.lm(par = start, fn = FCT, jac = jac,control = control, lower = lower, : evaluation of fn function returnsnon-sensible value! (#11)

 

 
I have not come across this error before with CIDR. You would have to send me the code & some data that reproduces this problem. Best to contact me with this information at m.troup@victorchang.edu.au
 
Michael

**Comment by croct** [comment]
This error message was created in the scDataConstructor function when the input data matrix is not "raw" (e.g. the user may have supplied logTPM data).  Note that the default "tagType" value is "raw".  The user can supply "cpm" data, and will need to change the "tagType" value accordingly.  See the help for scDataConstructor for more information.
